# Generated by ChatGPT Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0139_remove_account_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_domain',
            field=models.CharField(
                blank=True,
                help_text='Custom tenant domain used for domain-based multitenancy.',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='account',
            name='tenant_slug',
            field=models.SlugField(
                blank=True,
                help_text='Used to resolve tenants by subdomain.',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
